const express = require("express");
const { requireAuth, allowRoles } = require("../middleware/auth");
const controller = require("../controllers/vehicleController");
const router = express.Router();
router.use(requireAuth, allowRoles("customer"));
router.get("/", controller.listVehicles);
router.post("/", controller.addVehicle);
router.put("/:id", controller.updateVehicle);
router.delete("/:id", controller.deleteVehicle);
module.exports = router;